name: Deploy

on:
  push:
    branches:
      - ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Install dependencies
        run: npm i

    #   - name: Build the Angular app
    #     run: |
    #       npm run build
    #       $sourcePath = './dist/*'
    #       $zipFilePath = 'dist.zip'
    #       Compress-Archive -Path $sourcePath -DestinationPath $zipFilePath
      - name: Build the Angular app
        run: npm run build
            
        
      - name: compress dist
        run: tar -czvf dist.gz ./dist/fuse/*

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ vars.HOST }}
            username: ${{ vars.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ vars.PORT }}
            source: "dist.gz"
            target: C:\

      - name: Unzip dist on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ vars.HOST }}
            username: ${{ vars.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ vars.PORT }}
            script: tar -xvzf C:\dist.gz -C C:\dist

    # ssh  Administrator@3.137.200.55 'Expand-Archive -Path $filePath -DestinationPath $destinationPath'
      # - name: Unzip dist on remote server
      #   run: |
      #       ssh -tt ${{ vars.USERNAME }}@${{ vars.HOST }} 'tar -xvzf C:\dist.gz -C C:\dist'

